// Renders every icon file from the one brand geometry
// (lib/ui/core/brand_mark.dart), so the launcher, the themed icon, the
// notification icon and the first-run mark can never drift apart:
//
//   assets/icon/icon.png             the full square (legacy Android, iOS, web)
//   assets/icon/icon_foreground.png  adaptive foreground, on the 108 canvas
//   assets/icon/icon_monochrome.png  Android 13 themed-icon layer
//   android/.../drawable/ic_stat_herdr.xml  the status-bar icon (vector)
//
// Run from app/, then let flutter_launcher_icons cut the platform sizes:
//
//   flutter test screenshot_test/brand_assets_test.dart
//   dart run flutter_launcher_icons
//
// Not part of `flutter test`: the folder is `screenshot_test`, not `test`.
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:herdr_mobile/ui/core/brand_mark.dart';

const _px = 1024;
const _white = Color(0xFFFFFFFF);

Future<void> _png(String path, void Function(Canvas c) draw) async {
  final recorder = ui.PictureRecorder();
  draw(Canvas(recorder));
  final image = await recorder.endRecording().toImage(_px, _px);
  final data = await image.toByteData(format: ui.ImageByteFormat.png);
  File(path).writeAsBytesSync(data!.buffer.asUint8List());
}

String _n(double v) => v.toStringAsFixed(2).replaceFirst(RegExp(r'\.?0+$'), '');

typedef _G = BrandGeometry;

/// The status-bar icon: one white silhouette (Android keeps only alpha) on a
/// square viewport around the mark, so it fills the 24 dp icon.
String _notificationXml() {
  const side = 50.0;
  const o = _G.canvas / 2 - side / 2;
  String x(double v) => _n(v - o);
  final r = _n(_G.curl);
  final crook = 'M${x(_G.stemX)},${x(_G.foot)} L${x(_G.stemX)},${x(_G.top)} '
      'A$r,$r 0 0,0 ${x(_G.crookX)},${x(_G.top)} L${x(_G.crookX)},${x(_G.tipY)}';
  final shoulder = 'M${x(_G.stemX)},${x(_G.shoulderY)} '
      'A$r,$r 0 0,1 ${x(_G.legX)},${x(_G.shoulderY)} L${x(_G.legX)},${x(_G.foot)}';
  const d = _G.dotRadius;
  final dot = 'M${x(_G.dot.dx - d)},${x(_G.dot.dy)} a${_n(d)},${_n(d)} 0 1,0 ${_n(2 * d)},0 '
      'a${_n(d)},${_n(d)} 0 1,0 -${_n(2 * d)},0';
  return '''
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by app/screenshot_test/brand_assets_test.dart from
     lib/ui/core/brand_mark.dart: the brand mark (an h whose stem rises into
     a shepherd's crook, holding the agent that needs you) as a flat white
     shape, because Android tints status bar icons and drops anything that is
     not alpha. Edit the geometry there, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="${_n(side)}"
    android:viewportHeight="${_n(side)}">
    <path
        android:strokeColor="#FFFFFFFF"
        android:strokeWidth="${_n(_G.stroke)}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round"
        android:pathData="$crook $shoulder" />
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="$dot" />
</vector>
''';
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('brand assets', () async {
    const k = _px / BrandGeometry.canvas;
    const crop = (BrandGeometry.canvas - BrandGeometry.visible) / 2;

    // Full square: the tile and the mark as a launcher shows it (the central
    // 72 units fill the square).
    await _png('assets/icon/icon.png', (c) {
      c.drawRect(const Rect.fromLTWH(0, 0, _px * 1.0, _px * 1.0), Paint()..color = BrandGeometry.tile);
      c.scale(_px / BrandGeometry.visible);
      c.translate(-crop, -crop);
      BrandGeometry.paint(c);
    });
    // Adaptive layers: the whole 108 canvas, transparent, no inset (the
    // geometry already sits inside the safe circle).
    await _png('assets/icon/icon_foreground.png', (c) {
      c.scale(k);
      BrandGeometry.paint(c);
    });
    await _png('assets/icon/icon_monochrome.png', (c) {
      c.scale(k);
      BrandGeometry.paint(c, mono: _white);
    });
    File('android/app/src/main/res/drawable/ic_stat_herdr.xml').writeAsStringSync(_notificationXml());
  });
}
